"""PPO Trainer for OBELIX — Submission 6.

Critique of Submission 5 (Dueling DDQN + Frame Stacking) and rationale for PPO:
  • Submission 5 used off-policy DDQN: replay buffer adds lag between behaviour and
    learning, and the Huber-loss + target-net architecture requires careful tuning.
  • Q-value overestimation still occurs despite Dueling/Double tricks when rewards
    are highly sparse (attach/success events are rare vs dense -18 open-space steps).
  • Fixed seed per episode (`args.seed + ep`) → the box always spawns at the same
    relative positions → network memorises layout, poor generalisation.
  • No curriculum: training always at difficulty=0, but evaluation may use higher
    difficulties.
  • torch.load without weights_only=True raises a DeprecationWarning in PyTorch 2.x.

Why PPO for Submission 6:
  1. On-policy updates: each gradient step uses data generated by the *current*
     policy → no stale-data issue, more faithful credit assignment.
  2. Clipped surrogate objective: prevents catastrophic policy updates without the
     instability of TRPO's hard constraint.
  3. Shared Actor-Critic encoder: value function V(s) guides advantage estimation
     while policy π(a|s) is learned jointly → better sample efficiency.
  4. Entropy bonus: built-in exploration pressure prevents premature convergence.
  5. GAE (λ=0.95): lower-variance advantage estimates → more stable gradient signal.
  6. Curriculum support: --difficulty flag + automatic multi-seed rollouts → better
     generalisation across arena seeds.

Example run (overnight on Colab / local GPU):
  python submission-6/train_ppo.py \\
      --obelix_py ./obelix.py \\
      --out submission-6/weights.pth \\
      --epochs 800 --rollout_len 2048 --max_steps 2000 \\
      --difficulty 0 --scaling_factor 5 --arena_size 500 \\
      --ent_coef 0.01 --seed 42
"""

from __future__ import annotations

import argparse
import random
from collections import deque
from typing import List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

ACTIONS = ["L45", "L22", "FW", "R22", "R45"]
N_ACTIONS = len(ACTIONS)


# ── Frame stacking ─────────────────────────────────────────────────────────────

class FrameStack:
    """Stacks the last k observations into a single 1-D float32 vector."""

    def __init__(self, k: int = 4, obs_dim: int = 18):
        self.k = k
        self.obs_dim = obs_dim
        self._buf: deque = deque(maxlen=k)

    def reset(self, obs: np.ndarray) -> np.ndarray:
        for _ in range(self.k):
            self._buf.append(obs.copy())
        return self._get()

    def step(self, obs: np.ndarray) -> np.ndarray:
        self._buf.append(obs.copy())
        return self._get()

    def _get(self) -> np.ndarray:
        return np.concatenate(list(self._buf)).astype(np.float32)

    @property
    def dim(self) -> int:
        return self.k * self.obs_dim


# ── Actor-Critic network ───────────────────────────────────────────────────────

class ActorCritic(nn.Module):
    """Shared encoder → policy logits (actor) + scalar value (critic)."""

    def __init__(self, in_dim: int, n_actions: int = N_ACTIONS):
        super().__init__()
        self.shared = nn.Sequential(
            nn.Linear(in_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
        )
        self.policy_head = nn.Linear(128, n_actions)
        self.value_head  = nn.Linear(128, 1)

    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        h = self.shared(x)
        return self.policy_head(h), self.value_head(h).squeeze(-1)

    @torch.no_grad()
    def act(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Sample action, return (action, log_prob, value)."""
        logits, value = self.forward(x)
        dist  = torch.distributions.Categorical(logits=logits)
        action = dist.sample()
        return action, dist.log_prob(action), value

    def evaluate_actions(
        self, x: torch.Tensor, actions: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return (log_probs, values, entropy) for a batch of (state, action) pairs."""
        logits, values = self.forward(x)
        dist = torch.distributions.Categorical(logits=logits)
        return dist.log_prob(actions), values, dist.entropy()


# ── Advantage estimation ────────────────────────────────────────────────────────

def compute_gae(
    rewards: List[float],
    values: List[float],
    dones: List[bool],
    last_value: float,
    gamma: float = 0.99,
    lam: float = 0.95,
) -> Tuple[List[float], List[float]]:
    """Generalised Advantage Estimation (GAE-λ).

    Returns (advantages, discounted_returns).
    """
    n          = len(rewards)
    advantages = [0.0] * n
    returns    = [0.0] * n
    values_ext = values + [last_value]
    gae        = 0.0

    for t in reversed(range(n)):
        not_done  = 1.0 - float(dones[t])
        delta     = rewards[t] + gamma * values_ext[t + 1] * not_done - values_ext[t]
        gae       = delta + gamma * lam * not_done * gae
        advantages[t] = gae
        returns[t]    = gae + values[t]

    return advantages, returns


# ── Reward normalisation ───────────────────────────────────────────────────────

def normalise_reward(r: float) -> float:
    """Scale raw reward to a stable training range (same as submission-5 for comparability)."""
    return float(np.clip(r / 200.0, -1.0, 10.0))


# ── Env loader ─────────────────────────────────────────────────────────────────

def import_obelix(path: str):
    import importlib.util
    spec = importlib.util.spec_from_file_location("obelix_env", path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.OBELIX


# ── Rollout collection ─────────────────────────────────────────────────────────

def collect_rollout(
    env,
    model: ActorCritic,
    fs: FrameStack,
    rollout_len: int,
    device: torch.device,
    seed: int,
) -> Tuple[list, list, list, list, list, list, float, int]:
    """Collect exactly `rollout_len` environment steps using the current policy."""
    obs_list, act_list, logp_list, val_list, rew_list, done_list = [], [], [], [], [], []

    raw_obs = env.reset(seed=seed)
    s       = fs.reset(raw_obs)

    for _ in range(rollout_len):
        x = torch.tensor(s, dtype=torch.float32).unsqueeze(0).to(device)
        action, log_prob, value = model.act(x)

        a         = int(action.item())
        raw_obs2, raw_r, done2 = env.step(ACTIONS[a], render=False)
        s2  = fs.step(raw_obs2)
        r   = normalise_reward(float(raw_r))

        obs_list.append(s.copy())
        act_list.append(a)
        logp_list.append(float(log_prob.item()))
        val_list.append(float(value.item()))
        rew_list.append(r)
        done_list.append(bool(done2))

        s = s2
        if done2:
            seed   += 1          # vary the box/robot start position each episode
            raw_obs = env.reset(seed=seed)
            s       = fs.reset(raw_obs)

    # Bootstrap: estimate value at the last state reached
    x_last = torch.tensor(s, dtype=torch.float32).unsqueeze(0).to(device)
    with torch.no_grad():
        _, last_val = model(x_last)
    last_value = float(last_val.item()) if not done_list[-1] else 0.0

    return obs_list, act_list, logp_list, val_list, rew_list, done_list, last_value, seed


# ── PPO update ─────────────────────────────────────────────────────────────────

def ppo_update(
    model: ActorCritic,
    optimizer: optim.Optimizer,
    obs_t: torch.Tensor,
    act_t: torch.Tensor,
    old_logp_t: torch.Tensor,
    adv_t: torch.Tensor,
    ret_t: torch.Tensor,
    device: torch.device,
    clip_eps: float = 0.2,
    vf_coef: float = 0.5,
    ent_coef: float = 0.01,
    n_epochs: int = 4,
    batch_size: int = 256,
) -> dict:
    """Perform `n_epochs` passes of mini-batch PPO gradient updates."""
    n     = obs_t.shape[0]
    stats = {"pg_loss": 0.0, "vf_loss": 0.0, "entropy": 0.0, "n_updates": 0}

    for _ in range(n_epochs):
        perm = torch.randperm(n)
        for start in range(0, n, batch_size):
            idx = perm[start : start + batch_size]

            obs_b     = obs_t[idx]
            act_b     = act_t[idx]
            old_lp_b  = old_logp_t[idx]
            adv_b     = adv_t[idx]
            ret_b     = ret_t[idx]

            # Normalise advantages within the mini-batch
            adv_b = (adv_b - adv_b.mean()) / (adv_b.std() + 1e-8)

            log_probs, values, entropy = model.evaluate_actions(obs_b, act_b)

            ratio  = torch.exp(log_probs - old_lp_b)
            surr1  = ratio * adv_b
            surr2  = torch.clamp(ratio, 1.0 - clip_eps, 1.0 + clip_eps) * adv_b
            pg_loss = -torch.min(surr1, surr2).mean()

            vf_loss  = F.smooth_l1_loss(values, ret_b)
            ent_loss = -entropy.mean()           # minimise → maximise entropy
            loss     = pg_loss + vf_coef * vf_loss + ent_coef * ent_loss

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 0.5)
            optimizer.step()

            stats["pg_loss"]  += pg_loss.item()
            stats["vf_loss"]  += vf_loss.item()
            stats["entropy"]  += entropy.mean().item()
            stats["n_updates"] += 1

    return stats


# ── Training loop ──────────────────────────────────────────────────────────────

def train(args) -> None:
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    device = torch.device("cpu")

    OBELIX = import_obelix(args.obelix_py)
    fs     = FrameStack(k=args.frame_stack, obs_dim=18)

    # Single persistent env (avoids per-episode recreation overhead)
    env = OBELIX(
        scaling_factor=args.scaling_factor,
        arena_size=args.arena_size,
        max_steps=args.max_steps,
        wall_obstacles=args.wall_obstacles,
        difficulty=args.difficulty,
        box_speed=args.box_speed,
        seed=args.seed,
    )

    model     = ActorCritic(in_dim=fs.dim, n_actions=N_ACTIONS).to(device)
    optimizer = optim.Adam(model.parameters(), lr=args.lr)

    best_mean      = float("-inf")
    recent_returns = deque(maxlen=50)
    seed           = args.seed
    total_steps    = 0

    for epoch in range(args.epochs):
        model.train()
        (
            obs_list, act_list, logp_list, val_list,
            rew_list, done_list, last_value, seed,
        ) = collect_rollout(env, model, fs, args.rollout_len, device, seed)

        total_steps += args.rollout_len

        # GAE
        advantages, returns = compute_gae(
            rew_list, val_list, done_list, last_value,
            gamma=args.gamma, lam=args.lam,
        )

        # Convert to tensors
        obs_t      = torch.tensor(np.array(obs_list),    dtype=torch.float32).to(device)
        act_t      = torch.tensor(np.array(act_list),    dtype=torch.long).to(device)
        old_logp_t = torch.tensor(np.array(logp_list),   dtype=torch.float32).to(device)
        adv_t      = torch.tensor(np.array(advantages),  dtype=torch.float32).to(device)
        ret_t      = torch.tensor(np.array(returns),     dtype=torch.float32).to(device)

        stats = ppo_update(
            model, optimizer, obs_t, act_t, old_logp_t, adv_t, ret_t,
            device,
            clip_eps   = args.clip_eps,
            vf_coef    = args.vf_coef,
            ent_coef   = args.ent_coef,
            n_epochs   = args.update_epochs,
            batch_size = args.batch_size,
        )

        # Accumulate episode returns from this rollout (raw reward, not normalised)
        ep_ret = 0.0
        for r_norm, done in zip(rew_list, done_list):
            ep_ret += r_norm * 200.0    # un-normalise for interpretable logging
            if done:
                recent_returns.append(ep_ret)
                ep_ret = 0.0

        # Logging
        if (epoch + 1) % 10 == 0:
            mean_ret = float(np.mean(recent_returns)) if recent_returns else float("nan")
            n_upd    = max(stats["n_updates"], 1)
            print(
                f"epoch={epoch+1:4d} | mean50={mean_ret:9.1f} | "
                f"pg={stats['pg_loss']/n_upd:.4f} | "
                f"vf={stats['vf_loss']/n_upd:.4f} | "
                f"ent={stats['entropy']/n_upd:.4f} | "
                f"steps={total_steps}"
            )
            if len(recent_returns) >= 10 and mean_ret > best_mean:
                best_mean = mean_ret
                torch.save(model.state_dict(), args.out)
                print(f"  → New best ({best_mean:.1f})! Saved to {args.out}")

    print(f"\nTraining done. Best mean50={best_mean:.1f}. Weights: {args.out}")


# ── CLI ────────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(description="PPO Trainer for OBELIX — Submission 6")
    ap.add_argument("--obelix_py",       type=str,   required=True)
    ap.add_argument("--out",             type=str,   default="weights.pth")
    ap.add_argument("--epochs",          type=int,   default=800)
    ap.add_argument("--rollout_len",     type=int,   default=2048)
    ap.add_argument("--max_steps",       type=int,   default=2000)
    ap.add_argument("--difficulty",      type=int,   default=0)
    ap.add_argument("--wall_obstacles",  action="store_true")
    ap.add_argument("--box_speed",       type=int,   default=2)
    ap.add_argument("--scaling_factor",  type=int,   default=5)
    ap.add_argument("--arena_size",      type=int,   default=500)
    ap.add_argument("--frame_stack",     type=int,   default=4)
    # PPO hyperparams
    ap.add_argument("--gamma",           type=float, default=0.99)
    ap.add_argument("--lam",             type=float, default=0.95)
    ap.add_argument("--lr",              type=float, default=3e-4)
    ap.add_argument("--clip_eps",        type=float, default=0.2)
    ap.add_argument("--vf_coef",         type=float, default=0.5)
    ap.add_argument("--ent_coef",        type=float, default=0.01)
    ap.add_argument("--update_epochs",   type=int,   default=4)
    ap.add_argument("--batch_size",      type=int,   default=256)
    ap.add_argument("--seed",            type=int,   default=42)
    args = ap.parse_args()
    train(args)


if __name__ == "__main__":
    main()
